Creating CRUD Posts
lancamonica/quasar-blog pull request #3
Opened 2021-10-21 15:00 UTC by lancamonica

2021-10-21 15:09 UTC, felipejuzo02 commented on src/pages/posts/DetailsPost.vue
> +    <div v-if="!this.$route.query.id || isEditImage">
lógicas evite fazer no template, crie uma computada e chame ela

2021-10-21 15:09 UTC, felipejuzo02 commented on src/pages/posts/DetailsPost.vue
> +      <q-btn v-if="this.$route.query.id" color="brand" label="Excluir" @click="isOpenModal = true"/>
evitar usar lógica no template, nesse caso, crie um método e chame ele

2021-10-21 15:09 UTC, felipejuzo02 commented on src/pages/posts/DetailsPost.vue
> +          <q-btn flat label="Cancelar" color="brand" @click="isOpenModal = false" />
mesma coisa

2021-10-21 15:09 UTC, felipejuzo02 commented on src/pages/posts/DetailsPost.vue
> +    }
ta usando essa classe em algum lugar? n achei ela

2021-10-21 15:09 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +          <q-btn flat label="Cancelar" color="brand" @click="isOpenModal = false" />
colocar a logica em um metodo

2021-10-21 15:09 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +    }
ta usando em algum lugar? n encontrei

2021-10-21 15:09 UTC, felipejuzo02 commented on src/store/modules/posts.js
> +    state.deletePost = data
dar um espaço entre cada mutation

2021-10-21 15:41 UTC, eliasassuncao requested changes

2021-10-21 15:41 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +            <q-breadcrumbs-el class="q-ml-md cursor-pointer non-selectable" label="Home" icon="home" @click="handleHome" />
não existe um `to` pra o `breadcrumb` ? tenta utilizar `:to="{ { name: 'PostsList' } } "`

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +    <div v-if="!this.$route.query.id || isEditImage">
lógica na view, cria uma computada pra essa validação

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +      <q-btn color="brand q-mr-sm" label="Voltar" @click="$router.go(-1)"/>
espaço antes de fechar a tag `/>`

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +      <q-btn color="brand q-mr-sm" label="Salvar" @click="handleSave"/>
espaço antes de fechar a tag `/>`

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +      <q-btn v-if="this.$route.query.id" color="brand" label="Excluir" @click="isOpenModal = true"/>
não precisa do `this` na view, porém é bom vc criar uma computada pra isso, pra validar as chaves e não correr o risco de crashar a página

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +          <q-btn flat label="Cancelar" color="brand" @click="isOpenModal = false" />
lógica na view, criar um método pra isso

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +        lastChange: this.detailsPost.lastChange = date.formatDate(new Date(), 'DD/MM/YYYY'),
utilizamos o padrão de nome de chave para mudanças como `updatedAt`

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +      await this.addPost(data)
dessa forma ele não vai atualizar o post e dps criar um post? não deveria fazer somente uma das ações?

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +<template>
nome de página não está seguindo nosso padrão e está meio confuso...
utilizamos o padrão da seguinte forma:

```
PostsList -> listagem de posts
PostsEdit -> formulario de edição do post
PostsCreate -> formulario de criação do post
PostsForm -> quando utilizamos o mesmo formulário para criar e editar
```

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +    <q-dialog v-model="isOpenModal" persistent>
isso não poderia ser um componente?

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +</script>
vc está com o eslint instalado? parece q não tá salvando na ordem `name, computed, methods, etc`

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +      width: 100%;
utilizar classe `full-width` do quasar

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/DetailsPost.vue
> +      background: $dark-grey;
utilizar a classe `bg-grey` não resolve?

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    <q-dialog v-model="isOpenModal" persistent>
poderia ser um componente

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      this.$router.push({ name: 'DetailsPost' })
não funciona utilizando o `to` ?

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    handleEdit (id) {
o nome está meio sem sentido, pq não existe nenhuma lógica na função

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      size: 'md',
size não precisa ser um data, pode passar direto

2021-10-21 15:41 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      background: $dark-grey;
classe bg-grey não funciona?

2021-10-21 15:41 UTC, eliasassuncao commented on src/router/routes.js
> +      { path: 'post', name: 'DetailsPostEdit', component: () => import('pages/posts/DetailsPost.vue') }
utilizar padrão de nome de rota e nome da página

2021-10-21 16:11 UTC, felipejuzo02 commented on src/pages/posts/DetailsPost.vue
> +<template>
nessa caso se remete ao detalhe do post certo? então seria
`PostsSingle` não? @eliasassuncao

2021-10-21 17:05 UTC, lancamonica commented on src/pages/posts/DetailsPost.vue
> +    }
estou usando no color dos icons e botões

2021-10-21 17:07 UTC, lancamonica commented on src/pages/posts/PostsList.vue
> +    }
estou usando no color dos icons e botões

2021-10-21 17:27 UTC, lancamonica commented on src/pages/posts/DetailsPost.vue
> +<template>
@felipejuzo02 ao detalhe e a criação, fiz tudo no mesmo arquivo

2021-10-21 17:29 UTC, lancamonica commented on src/pages/posts/DetailsPost.vue
> +</script>
está instalado sim

2021-10-21 17:30 UTC, lancamonica commented on src/pages/posts/DetailsPost.vue
> +    <q-dialog v-model="isOpenModal" persistent>
você se refere ao q-dialog? como estou usando ele da forma que está no quasar, acredito que não precisaria de componente já que não estou passando nada específico pra ele

2021-10-21 17:31 UTC, lancamonica commented on src/pages/posts/DetailsPost.vue
> +      background: $dark-grey;
resolve, porem como estou usando a mesma cor em vários lugares, acredito que criando uma variável e chamando a classe em todos lugares pode facilitar se precisar mudar a cor

2021-10-21 17:31 UTC, lancamonica commented on src/pages/posts/PostsList.vue
> +    <q-dialog v-model="isOpenModal" persistent>
você se refere ao q-dialog? como estou usando ele da forma que está no quasar, acredito que não precisaria de componente já que não estou passando nada específico pra ele

2021-10-21 17:34 UTC, lancamonica commented on src/pages/posts/PostsList.vue
> +      background: $dark-grey;
funciona, porem como estou usando a mesma cor em vários lugares, acredito que criando uma variável e chamando a classe em todos lugares pode facilitar se precisar mudar a cor

2021-10-21 19:07 UTC, eliasassuncao requested changes

2021-10-21 19:07 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      <q-btn color="grey-4" text-color="brand" glossy unelevated icon="camera_enhance" label="Editar" @click="isEditImage = true" />
logica na view (@click), criar método

2021-10-21 19:07 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +        this.$router.push({ name: 'PostsList' })
poderia ser `return this.$router.push({ name: 'PostsList' })`

2021-10-21 19:07 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      size: 'md',
size poderia passar diretamente la encima, está criando uma variável reativa sem necessidade.

2021-10-21 20:15 UTC, felipejuzo02 approved these changes

2021-10-21 20:15 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +  <div class="page-post q-pa-lg">
nome da classe deveria ser `page-post-form` nao?

2021-10-22 20:33 UTC, eliasassuncao approved these changes

2021-10-25 12:01 UTC, juliadelisposte approved these changes

2021-10-25 13:53 UTC, cassioalmeida2 commented on src/pages/posts/PostsForm.vue
> +      <q-btn color="brand q-mr-sm" label="Voltar" @click="$router.go(-1) "/>
usar o router.go dentro de um método, por exemplo: cancel () { this.$router.go(-1) }

2021-10-25 13:53 UTC, cassioalmeida2 commented on src/store/modules/authors.js
> +    console.log(params)
remover console.log

2021-10-25 14:19 UTC, lancamonica commented on src/pages/posts/PostsForm.vue
> +      <q-btn color="brand q-mr-sm" label="Voltar" @click="$router.go(-1) "/>
resolvido

2021-10-25 14:20 UTC, lancamonica commented on src/store/modules/authors.js
> +    console.log(params)
resolvido

2021-10-25 14:21 UTC, cassioalmeida2 approved these changes

2021-10-25 14:22 UTC, merged